repos:
  - repo: https://github.com/PyCQA/isort
    rev: e44834b7b294701f596c9118d6c370f86671a50d # 5.12.0
    hooks:
      - id: isort
        args: ['--settings-path', 'pyproject.toml']
  - repo: https://github.com/psf/black
    rev: e87737140f32d3cd7c44ede75f02dcd58e55820e # 23.9.1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 7ef0350a439c93166bc8ba89fcc3de6a9a664e6c # 6.1.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 08cbc46b6e135adec84911b20e98e5bc52032152 # v1.5.1
    hooks:
      - id: mypy
        require_serial: true
        additional_dependencies: [
          types-requests>2,
          marshmallow>3
        ]
        exclude: tests|examples