[project]
name = "passwordless"
authors = []
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Programming Language :: Python :: 3",
    "Intended Audience :: Developers",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Security",
    "Topic :: Software Development :: Libraries",
    "License :: OSI Approved :: Apache Software License"
]
dynamic = ["version", "description"]
requires-python = ">=3.7"
keywords = ["passwordless", "bitwarden"]
dependencies = [
    "requests > 2",
    "marshmallow > 3"
]

[project.optional-dependencies]
dotenv = ["python-dotenv"]

[project.urls]
Home = "https://bitwarden.com/products/passwordless"
Documentation = "https://docs.passwordless.dev/guide"
Source = "https://github.com/passwordless/passwordless-python"

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
    "error",
]

[tool.mypy]
python_version = "3.8"
files = ["src/passwordless"]
show_error_codes = true
pretty = true
strict = true
#allow_redefinition = true
#disallow_subclassing_any = true
#disallow_untyped_calls = true
#disallow_untyped_defs = true
#disallow_incomplete_defs = true
#no_implicit_optional = true
#local_partial_types = true
#no_implicit_reexport = true
#strict_equality = true
#warn_redundant_casts = true
#warn_unused_configs = true
#warn_unused_ignores = true
#warn_return_any = true
#warn_unreachable = true

[[tool.mypy.overrides]]
module = [
    "asgiref.*",
    "dotenv.*",
    "cryptography.*",
    "importlib_metadata",
]
ignore_missing_imports = true

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "passwordless"

[tool.flit.sdist]
include = [
    "requirements/",
    "tests/",
    "tox.ini",
]
exclude = [
    "docs/_build/",
]