name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.8
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: '3.8'
          cache: 'poetry'
      - name: Build
        run: poetry install --with dev,test
      - name: Run isort
        run: poetry run isort . --check-only
      - name: Run docformatter
        run: poetry run docformatter --in-place --config ./pyproject.toml src/
      - name: Run black
        run: poetry run black . --check
      - name: Run flake8
        run: poetry run flake8 .
      - name: Run mypy
        run: poetry run mypy .
      - name: Test
        run: poetry run pytest
