name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-sdk:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: '3.9'
          cache: 'poetry'
      - name: Setup
        run: poetry env use 3.9
      - name: Environment information
        run: poetry env info
      - name: Build
        run: poetry install --with dev,test
      - name: Run isort
        run: poetry run isort . --check-only
      - name: Run docformatter
        run: poetry run docformatter --in-place --config ./pyproject.toml src/
      - name: Run black
        run: poetry run black . --check
      - name: Run flake8
        run: poetry run flake8 .
      - name: Run mypy
        run: poetry run mypy .
      - name: Test
        run: poetry run pytest

  build-flask-example:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: '3.9'
          cache: 'poetry'
      - name: Setup
        run: poetry env use 3.9
      - name: Environment information
        run: poetry env info
      - name: Build
        run: |
          cd examples/flask;
          poetry install --with dev

  build-streamlit-example:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: '3.9'
          cache: 'poetry'
      - name: Setup
        run: poetry env use 3.9
      - name: Environment information
        run: poetry env info
      - name: Build
        run: |
          cd examples/streamlit;
          poetry install --with dev